version: 0.2

phases:
  install:
    commands:
      - echo Started Install Phase
  pre_build:
    commands:
      - echo Started Pre-Build Phase
      - npm install --omit=dev
  build:
    commands:
      - npm run build