version: 0.2

phases:
  install:
    commands:
      - echo Started Install Phase
  pre_build:
    commands:
      - echo Started Pre-Build Phase
      - npm install
  build:
    commands:
      - echo Started Build Phase
      - npm run build --verbose
  post_build:
    commands:
      - echo Started Post-Build Phase
      - aws s3 sync dist s3://cw.kn6vzx.radio/ --debug